version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: app_stop.sh
      timeout: 200
      runas: root
  ApplicationStart:
    - location: app_start.sh
      timeout: 200
      runas: root