spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cfbdb
    username: root
    password: root
  jpa:
    show-sql: true
  autoconfigure:
      exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
server:
  port: 8081

app:
  cors:
    allowedOrigins: http://localhost:4200,http://localhost:8081
