spring:
  datasource:
    url: jdbc:mysql://db-test.cdqqz91vmmlb.us-east-2.rds.amazonaws.com:3306/cfbdb
    username: root
    password: $Complex505
  autoconfigure:
      exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
server:
  port: 8081
logging:
  file:
    name: cfbh.log
