spring:
  datasource:
    url: jdbc:mysql://db-test.cdqqz91vmmlb.us-east-2.rds.amazonaws.com:3306/cfbdb
    username: root
    password: ${DB_PASSWORD}
  autoconfigure:
      exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
server:
  port: 8081

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8081
